# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: /Users/distiller/project/output
      FASTLANE_LANE: test
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run: mkdir $FL_OUTPUT_DIR
      - run: bundle install
      # Build the app and run tests
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - run:
          command: cp $FL_OUTPUT_DIR/scan/report.junit $FL_OUTPUT_DIR/scan/report.xml
          when: always
      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_artifacts:
          path: /Users/distiller/project/output
      - store_test_results:
          path: /Users/distiller/project/output/scan

  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - run: mkdir $CIRCLE_TEST_REPORTS/django
      - run:
          command: cp result.xml $CIRCLE_TEST_REPORTS/django/result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
#  danger:
#    docker:
#      - image: dantoml/danger:latest
#    steps:
#      - checkout
#      - run: danger

workflows:
  version: 2
  build-test-lint:
    jobs:
      - swiftlint
#      - danger
      - build


